### ISSUE TITLE
Missing (non-dev) dependency?

### ISSUE THREAD

**Issue by AllenJB** [razorpay/slack#20]
Version: 1.9.9

PHP Fatal error:  Trait 'Illuminate\Foundation\Bus\DispatchesJobs' not found in /var/www/vhosts/project/vendor/razorpay/slack/src/Client.php on line 13

It looks like a dependency has been introduced on Illuminate/Foundation, but this isn't reflected in composer.json

**Comment by gaurav1068** [comment]
@AllenJB will fix this and create a PR

**Comment by gaurav1068** [comment]
fixe din 1.9.10

**Comment by gaurav1068** [comment]
Fix not working in the expecting way reopening it

**Comment by lots0logs** [comment]
Just wanted to note that this still appears to be an issue.

**Comment by gaurav1068** [comment]
@AllenJB @lots0logs fixed in tag 1.10.0, plz check and reopen if issue persists
