### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by Mopster** [razorpay/slack#8]
Hi,
 
Looks like this fork seems the most updated. I'm looking for an updated repo to fix the 5.4 `Application::share()` break.

I see the PR https://github.com/razorpay/slack/pull/2 has it in there, with a lot of other changes. Since it looks like a small change just for 5.4 support, can this be updated separately soon?

**Comment by gaurav1068** [comment]
Hi,  
@Mopster, if you want you can use  f/queue-with-retry branch , which is forked from the base repo, but it has diverged from mkanz/slack master , We are working on Releasing a newer version but it may take time. As (maknz/slack will no longer maintained)

Please note the changes are mainly for using queue with the original repo and also retry on send via queue if send fails, and coding standard changes.

If your use case is normal things will work without any problem for you.
Let me know if you are having any poblem using the branch.

**Comment by Mopster** [comment]
Thanks. :-)

**Comment by gaurav1068** [comment]
We have Released https://github.com/razorpay/slack-laravel/releases/tag/1.2.0 which uses https://github.com/razorpay/slack/releases/tag/1.8.0. You can use that. If you have any problem using that please refer README or open issue in the repo. Closing the issue
